management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: servicio-items
  config:
    import: configserver:http://localhost:8888
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8002
